package net.noiraude.creditseditor.resource;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.nio.file.FileSystem;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Set;

import net.noiraude.libcredits.lang.LangDocument;
import net.noiraude.libcredits.lang.LangParser;
import net.noiraude.libcredits.model.CreditsDocument;
import net.noiraude.libcredits.pack.CreditsLayout;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

@SuppressWarnings("SpellCheckingInspection")
public class ResourceManagerTest {

    private static final String TEST_PACK_DESCRIPTION = "test pack";

    @TempDir
    Path temp;

    @Test
    public void exists_directory_isTrue() throws Exception {
        Path dir = Files.createDirectory(temp.resolve("root"));
        assertTrue(ResourceManager.exists(dir.toString()));
    }

    @Test
    public void exists_zipFile_isTrue() throws Exception {
        Path zip = temp.resolve("pack.zip");
        // noinspection EmptyTryBlock
        try (ResourceManager ignored = ResourceManager.create(zip.toString(), TEST_PACK_DESCRIPTION)) {
            // Created on disk; close before re-querying.
        }
        assertTrue(ResourceManager.exists(zip.toString()));
    }

    @Test
    public void exists_missingPath_isFalse() {
        assertFalse(
            ResourceManager.exists(
                temp.resolve("nope")
                    .toString()));
    }

    @Test
    public void exists_unsupportedFile_isFalse() throws Exception {
        Path other = temp.resolve("notes.txt");
        Files.writeString(other, "hello", StandardCharsets.UTF_8);
        assertFalse(ResourceManager.exists(other.toString()));
    }

    @Test
    public void open_missingPath_throws() {
        assertThrows(IOException.class, () -> {
            // noinspection EmptyTryBlock
            try (ResourceManager ignored = ResourceManager.open(
                temp.resolve("nope")
                    .toString())) {
                // Expected to throw before reaching here.
            }
        });
    }

    @Test
    public void create_existingPath_throws() throws Exception {
        Path dir = Files.createDirectory(temp.resolve("root"));
        assertThrows(IOException.class, () -> ResourceManager.create(dir.toString(), TEST_PACK_DESCRIPTION));
    }

    @Test
    public void create_directoryBackend_seedsPackMcmeta() throws Exception {
        Path dir = temp.resolve("newdir");
        // noinspection EmptyTryBlock
        try (ResourceManager ignored = ResourceManager.create(dir.toString(), "directory pack desc")) {
            // Created on disk; we only assert the seed contents below.
        }
        Path mcmeta = dir.resolve("pack.mcmeta");
        assertTrue(Files.exists(mcmeta), "directory backend must seed pack.mcmeta on create");
        String text = Files.readString(mcmeta, StandardCharsets.UTF_8);
        assertTrue(text.contains("\"pack_format\": 1"));
        assertTrue(text.contains("directory pack desc"));
    }

    @Test
    public void create_zipBackend_seedsPackMcmetaWithSuppliedDescription() throws Exception {
        Path zip = temp.resolve("new-pack.zip");
        // noinspection EmptyTryBlock
        try (ResourceManager ignored = ResourceManager
            .create(zip.toString(), "Generated by GTNH Credits Editor 1.2.3")) {
            // Created on disk; assertions below open the zip directly.
        }
        URI uri = URI.create("jar:" + zip.toUri());
        try (FileSystem fs = FileSystems.newFileSystem(uri, Map.<String, String>of())) {
            Path mcmeta = fs.getPath("/pack.mcmeta");
            assertTrue(Files.exists(mcmeta));
            String text = Files.readString(mcmeta, StandardCharsets.UTF_8);
            assertTrue(text.contains("\"pack_format\": 1"));
            assertTrue(text.contains("Generated by GTNH Credits Editor"));
        }
    }

    @Test
    public void open_emptyDirectory_loadsEmptyDocuments() throws Exception {
        Path dir = Files.createDirectory(temp.resolve("root"));

        try (ResourceManager rm = ResourceManager.open(dir.toString())) {
            rm.loadDocuments();
            assertTrue(rm.getCreditsDoc().categories.isEmpty());
            assertTrue(rm.getCreditsDoc().persons.isEmpty());
            assertFalse(rm.isDirty());
        }
    }

    @Test
    public void open_directoryWithCreditsJsonButNoLangDir_loadsCreditsAndEmptyLang() throws Exception {
        Path dir = Files.createDirectory(temp.resolve("root"));
        Path creditsJson = dir.resolve(CreditsLayout.CREDITS.get());
        Files.createDirectories(creditsJson.getParent());
        Files.writeString(creditsJson, "{\"version\":2,\"category\":[],\"person\":[]}\n", StandardCharsets.UTF_8);

        try (ResourceManager rm = ResourceManager.open(dir.toString())) {
            rm.loadDocuments();
            assertTrue(rm.getCreditsDoc().categories.isEmpty());
            assertFalse(rm.isDirty(), "loading a missing lang directory must not mark the document dirty");
        }
    }

    @Test
    public void create_freshZip_loadsEmptyDocuments() throws Exception {
        Path zip = temp.resolve("fresh.zip");

        try (ResourceManager rm = ResourceManager.create(zip.toString(), TEST_PACK_DESCRIPTION)) {
            rm.loadDocuments();
            assertTrue(rm.getCreditsDoc().categories.isEmpty());
            assertTrue(rm.getCreditsDoc().persons.isEmpty());
            assertFalse(rm.isDirty());
        }
    }

    @Test
    public void open_directoryWithLangFiles_loadsAllLocales() throws Exception {
        Path dir = Files.createDirectory(temp.resolve("root"));
        Path langDir = dir.resolve(CreditsLayout.LANG_DIR.get());
        Files.createDirectories(langDir);
        Files.writeString(langDir.resolve("en_US.lang"), "credits.category.team=Team\n", StandardCharsets.UTF_8);
        Files.writeString(langDir.resolve("fr_FR.lang"), "credits.category.team=Equipe\n", StandardCharsets.UTF_8);

        try (ResourceManager rm = ResourceManager.open(dir.toString())) {
            rm.loadDocuments();

            assertEquals(Set.of("en_US", "fr_FR"), rm.availableLocales());

            LangDocument en = rm.langDoc("en_US")
                .orElseThrow();
            LangDocument fr = rm.langDoc("fr_FR")
                .orElseThrow();
            assertEquals("Team", en.get("credits.category.team"));
            assertEquals("Equipe", fr.get("credits.category.team"));
            assertSame(en, rm.getLangDoc(), "no-arg getLangDoc() must return the en_US document");

            assertTrue(
                rm.langDoc("de_DE")
                    .isEmpty());
            assertFalse(rm.isDirty(), "freshly loaded documents must not be dirty");
        }
    }

    @Test
    public void addLocale_seedsEmptyDocumentAndIsIdempotent() throws Exception {
        Path dir = Files.createDirectory(temp.resolve("root"));

        try (ResourceManager rm = ResourceManager.open(dir.toString())) {
            rm.loadDocuments();
            assertEquals(Set.of("en_US"), rm.availableLocales());

            rm.addLocale("de_DE");
            LangDocument added = rm.langDoc("de_DE")
                .orElseThrow();
            assertFalse(added.contains("credits.category.team"));
            assertEquals(Set.of("en_US", "de_DE"), rm.availableLocales());

            rm.addLocale("de_DE");
            assertSame(
                added,
                rm.langDoc("de_DE")
                    .orElseThrow(),
                "addLocale must be idempotent");
        }
    }

    @Test
    public void removeLocale_dropsDocumentFromMemoryAndStripsOwnedKeysOnSave() throws Exception {
        Path dir = Files.createDirectory(temp.resolve("root"));
        Path langDir = dir.resolve(CreditsLayout.LANG_DIR.get());
        Files.createDirectories(langDir);
        Files.writeString(langDir.resolve("en_US.lang"), "", StandardCharsets.UTF_8);
        Files.writeString(
            langDir.resolve("fr_FR.lang"),
            "gui.credits.title=Credits\ncredits.category.team=Equipe\ncredits.person.role.dev=Developpeur\n",
            StandardCharsets.UTF_8);

        try (ResourceManager rm = ResourceManager.open(dir.toString())) {
            rm.loadDocuments();
            LangDocument frBeforeRemoval = rm.langDoc("fr_FR")
                .orElseThrow();
            assertEquals("Equipe", frBeforeRemoval.get("credits.category.team"));

            rm.removeLocale("fr_FR");
            assertEquals(Set.of("en_US"), rm.availableLocales());
            assertTrue(
                rm.langDoc("fr_FR")
                    .isEmpty());

            rm.removeLocale("fr_FR"); // second call is a no-op
            assertEquals(Set.of("en_US"), rm.availableLocales());

            assertTrue(rm.isDirty(), "pending removal must mark the manager dirty");
            rm.writeLang();

            Path frPath = langDir.resolve("fr_FR.lang");
            assertTrue(Files.exists(frPath), "writeLang must keep the file when foreign keys remain");
            String written = Files.readString(frPath, StandardCharsets.UTF_8);
            assertTrue(written.contains("gui.credits.title=Credits"), "foreign key must survive locale removal");
            assertFalse(written.contains("credits.category.team"), "owned category key must be stripped");
            assertFalse(written.contains("credits.person.role.dev"), "owned role key must be stripped");
        }
    }

    @Test
    public void removeLocale_writeLang_isNoOpWhenFileMissing() throws Exception {
        Path dir = Files.createDirectory(temp.resolve("root"));

        try (ResourceManager rm = ResourceManager.open(dir.toString())) {
            rm.loadDocuments();
            rm.addLocale("fr_FR");
            LangDocument fr = rm.langDoc("fr_FR")
                .orElseThrow();
            fr.set("credits.category.team", "Equipe");
            rm.removeLocale("fr_FR");

            rm.writeLang();

            Path langDir = dir.resolve(CreditsLayout.LANG_DIR.get());
            assertFalse(
                Files.exists(langDir.resolve("fr_FR.lang")),
                "no file should be created for a locale that was never persisted");
        }
    }

    @Test
    public void writeLang_preservesForeignKeysAtDestination() throws Exception {
        Path dir = Files.createDirectory(temp.resolve("root"));
        Path langDir = dir.resolve(CreditsLayout.LANG_DIR.get());
        Files.createDirectories(langDir);
        Files.writeString(
            langDir.resolve("en_US.lang"),
            "gui.credits.title=Credits\ncredits.category.team=Old\n",
            StandardCharsets.UTF_8);

        try (ResourceManager rm = ResourceManager.open(dir.toString())) {
            rm.loadDocuments();
            LangDocument en = rm.getLangDoc();
            en.set("credits.category.team", "New");

            rm.writeLang();

            String written = Files.readString(langDir.resolve("en_US.lang"), StandardCharsets.UTF_8);
            assertTrue(written.contains("gui.credits.title=Credits"), "foreign key must remain");
            assertTrue(written.contains("credits.category.team=New"), "owned key must reflect the new value");
            assertFalse(written.contains("credits.category.team=Old"), "old owned value must be gone");
        }
    }

    @Test
    public void writeAllLang_overExistingDestination_preservesForeignKeys() throws Exception {
        Path destDir = Files.createDirectory(temp.resolve("dest"));
        Path destLangDir = destDir.resolve(CreditsLayout.LANG_DIR.get());
        Files.createDirectories(destLangDir);
        Files.writeString(
            destLangDir.resolve("en_US.lang"),
            "gui.credits.title=Credits\ncredits.category.team=DestOld\n",
            StandardCharsets.UTF_8);

        LangDocument sourceEn = LangParser.empty();
        sourceEn.set("credits.category.team", "FromSource");
        Map<String, LangDocument> sourceLangs = new LinkedHashMap<>();
        sourceLangs.put("en_US", sourceEn);

        try (ResourceManager dest = ResourceManager.open(destDir.toString())) {
            dest.adoptDocuments(CreditsDocument.empty(), sourceLangs);
            dest.writeAllLang();
        }

        String written = Files.readString(destLangDir.resolve("en_US.lang"), StandardCharsets.UTF_8);
        assertTrue(written.contains("gui.credits.title=Credits"), "foreign key at destination must survive Save As");
        assertTrue(written.contains("credits.category.team=FromSource"), "owned key must reflect the source value");
        assertFalse(
            written.contains("credits.category.team=DestOld"),
            "destination's old owned value must be replaced");
    }

    @Test
    public void writeLang_writesEveryDirtyLocale_andClearsDirtyAfterReload() throws Exception {
        Path dir = Files.createDirectory(temp.resolve("root"));
        Path langDir = dir.resolve(CreditsLayout.LANG_DIR.get());
        Files.createDirectories(langDir);
        Files.writeString(langDir.resolve("en_US.lang"), "credits.category.team=Team\n", StandardCharsets.UTF_8);
        Files.writeString(langDir.resolve("fr_FR.lang"), "credits.category.team=Equipe\n", StandardCharsets.UTF_8);

        try (ResourceManager rm = ResourceManager.open(dir.toString())) {
            rm.loadDocuments();
            rm.langDoc("en_US")
                .orElseThrow()
                .set("credits.category.team", "Team!");
            rm.langDoc("fr_FR")
                .orElseThrow()
                .set("credits.category.team", "Equipe!");

            rm.writeLang();
        }

        try (ResourceManager rm2 = ResourceManager.open(dir.toString())) {
            rm2.loadDocuments();
            assertEquals(
                "Team!",
                rm2.langDoc("en_US")
                    .orElseThrow()
                    .get("credits.category.team"));
            assertEquals(
                "Equipe!",
                rm2.langDoc("fr_FR")
                    .orElseThrow()
                    .get("credits.category.team"));
            assertFalse(rm2.isDirty(), "freshly reloaded manager must not be dirty");
        }
    }
}
