package net.noiraude.creditseditor.resource;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertSame;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.nio.file.FileSystem;
import java.nio.file.FileSystems;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;
import java.util.Set;

import net.noiraude.libcredits.lang.LangDocument;
import net.noiraude.libcredits.pack.CreditsLayout;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

public class ResourceManagerTest {

    private static final String TEST_PACK_DESCRIPTION = "test pack";

    @TempDir
    Path temp;

    @Test
    public void exists_directory_isTrue() throws Exception {
        Path dir = Files.createDirectory(temp.resolve("root"));
        assertTrue(ResourceManager.exists(dir.toString()));
    }

    @Test
    public void exists_zipFile_isTrue() throws Exception {
        Path zip = temp.resolve("pack.zip");
        try (ResourceManager rm = ResourceManager.create(zip.toString(), TEST_PACK_DESCRIPTION)) {
            // Created on disk; close before re-querying.
        }
        assertTrue(ResourceManager.exists(zip.toString()));
    }

    @Test
    public void exists_missingPath_isFalse() {
        assertFalse(
            ResourceManager.exists(
                temp.resolve("nope")
                    .toString()));
    }

    @Test
    public void exists_unsupportedFile_isFalse() throws Exception {
        Path other = temp.resolve("notes.txt");
        Files.writeString(other, "hello", StandardCharsets.UTF_8);
        assertFalse(ResourceManager.exists(other.toString()));
    }

    @Test
    public void open_missingPath_throws() {
        assertThrows(
            IOException.class,
            () -> ResourceManager.open(
                temp.resolve("nope")
                    .toString()));
    }

    @Test
    public void create_existingPath_throws() throws Exception {
        Path dir = Files.createDirectory(temp.resolve("root"));
        assertThrows(IOException.class, () -> ResourceManager.create(dir.toString(), TEST_PACK_DESCRIPTION));
    }

    @Test
    public void create_directoryBackend_seedsPackMcmeta() throws Exception {
        Path dir = temp.resolve("newdir");
        try (ResourceManager rm = ResourceManager.create(dir.toString(), "directory pack desc")) {
            // Created on disk; we only assert the seed contents below.
        }
        Path mcmeta = dir.resolve("pack.mcmeta");
        assertTrue(Files.exists(mcmeta), "directory backend must seed pack.mcmeta on create");
        String text = Files.readString(mcmeta, StandardCharsets.UTF_8);
        assertTrue(text.contains("\"pack_format\": 1"));
        assertTrue(text.contains("directory pack desc"));
    }

    @Test
    public void create_zipBackend_seedsPackMcmetaWithSuppliedDescription() throws Exception {
        Path zip = temp.resolve("new-pack.zip");
        try (ResourceManager rm = ResourceManager.create(zip.toString(), "Generated by GTNH Credits Editor 1.2.3")) {
            // Created on disk; assertions below open the zip directly.
        }
        URI uri = URI.create("jar:" + zip.toUri());
        try (FileSystem fs = FileSystems.newFileSystem(uri, Map.<String, String>of())) {
            Path mcmeta = fs.getPath("/pack.mcmeta");
            assertTrue(Files.exists(mcmeta));
            String text = Files.readString(mcmeta, StandardCharsets.UTF_8);
            assertTrue(text.contains("\"pack_format\": 1"));
            assertTrue(text.contains("Generated by GTNH Credits Editor"));
        }
    }

    @Test
    public void open_emptyDirectory_loadsEmptyDocuments() throws Exception {
        Path dir = Files.createDirectory(temp.resolve("root"));

        try (ResourceManager rm = ResourceManager.open(dir.toString())) {
            rm.loadDocuments();
            assertTrue(rm.getCreditsDoc().categories.isEmpty());
            assertTrue(rm.getCreditsDoc().persons.isEmpty());
            assertFalse(rm.isDirty());
        }
    }

    @Test
    public void open_directoryWithCreditsJsonButNoLangDir_loadsCreditsAndEmptyLang() throws Exception {
        Path dir = Files.createDirectory(temp.resolve("root"));
        Path creditsJson = dir.resolve(CreditsLayout.CREDITS.get());
        Files.createDirectories(creditsJson.getParent());
        Files.writeString(creditsJson, "{\"version\":2,\"category\":[],\"person\":[]}\n", StandardCharsets.UTF_8);

        try (ResourceManager rm = ResourceManager.open(dir.toString())) {
            rm.loadDocuments();
            assertTrue(rm.getCreditsDoc().categories.isEmpty());
            assertFalse(rm.isDirty(), "loading a missing lang directory must not mark the document dirty");
        }
    }

    @Test
    public void create_freshZip_loadsEmptyDocuments() throws Exception {
        Path zip = temp.resolve("fresh.zip");

        try (ResourceManager rm = ResourceManager.create(zip.toString(), TEST_PACK_DESCRIPTION)) {
            rm.loadDocuments();
            assertTrue(rm.getCreditsDoc().categories.isEmpty());
            assertTrue(rm.getCreditsDoc().persons.isEmpty());
            assertFalse(rm.isDirty());
        }
    }

    @Test
    public void open_directoryWithLangFiles_loadsAllLocales() throws Exception {
        Path dir = Files.createDirectory(temp.resolve("root"));
        Path langDir = dir.resolve(CreditsLayout.LANG_DIR.get());
        Files.createDirectories(langDir);
        Files.writeString(langDir.resolve("en_US.lang"), "credits.category.team=Team\n", StandardCharsets.UTF_8);
        Files.writeString(langDir.resolve("fr_FR.lang"), "credits.category.team=Equipe\n", StandardCharsets.UTF_8);

        try (ResourceManager rm = ResourceManager.open(dir.toString())) {
            rm.loadDocuments();

            assertEquals(Set.of("en_US", "fr_FR"), rm.availableLocales());

            LangDocument en = rm.langDoc("en_US");
            LangDocument fr = rm.langDoc("fr_FR");
            assertNotNull(en);
            assertNotNull(fr);
            assertEquals("Team", en.get("credits.category.team"));
            assertEquals("Equipe", fr.get("credits.category.team"));
            assertSame(en, rm.getLangDoc(), "no-arg getLangDoc() must return the en_US document");

            assertNull(rm.langDoc("de_DE"));
            assertFalse(rm.isDirty(), "freshly loaded documents must not be dirty");
        }
    }

    @Test
    public void addLocale_seedsEmptyDocumentAndIsIdempotent() throws Exception {
        Path dir = Files.createDirectory(temp.resolve("root"));

        try (ResourceManager rm = ResourceManager.open(dir.toString())) {
            rm.loadDocuments();
            assertEquals(Set.of("en_US"), rm.availableLocales());

            LangDocument added = rm.addLocale("de_DE");
            assertNotNull(added);
            assertFalse(added.contains("credits.category.team"));
            assertEquals(Set.of("en_US", "de_DE"), rm.availableLocales());

            assertSame(added, rm.addLocale("de_DE"), "addLocale must be idempotent");
        }
    }

    @Test
    public void removeLocale_dropsDocumentFromMemoryAndDeletesFileOnSave() throws Exception {
        Path dir = Files.createDirectory(temp.resolve("root"));
        Path langDir = dir.resolve(CreditsLayout.LANG_DIR.get());
        Files.createDirectories(langDir);
        Files.writeString(langDir.resolve("en_US.lang"), "", StandardCharsets.UTF_8);
        Files.writeString(langDir.resolve("fr_FR.lang"), "credits.category.team=Equipe\n", StandardCharsets.UTF_8);

        try (ResourceManager rm = ResourceManager.open(dir.toString())) {
            rm.loadDocuments();
            LangDocument removed = rm.removeLocale("fr_FR");

            assertNotNull(removed);
            assertEquals("Equipe", removed.get("credits.category.team"));
            assertEquals(Set.of("en_US"), rm.availableLocales());
            assertNull(rm.langDoc("fr_FR"));
            assertNull(rm.removeLocale("fr_FR"), "second removeLocale returns null");

            assertTrue(rm.isDirty(), "pending deletion must mark the manager dirty");
            rm.writeLang();
            assertFalse(Files.exists(langDir.resolve("fr_FR.lang")), "writeLang must delete removed locale's file");
        }
    }
}
