annotationsVersion=26.0.2-1
modularUI2Version=2.3.45-1.7.10
customMainMenuVersion=1.14.0
junitVersion=4.13.2
junitJupiterVersion=5.10.2
jsonSchemaValidatorVersion=3.0.1
gsonVersion=2.8.9
flatLafVersion=3.5.4