name=GTNH Credits Editor
version=${version}
license=MIT License
author=Léa Gris
copyright=Copyright © 2025 Léa Gris
description=Open Source, Free Software
url=https://github.com/GTNewHorizons/GTNH-Credits
